version: "3.8"

services:
  postgres:
    image: postgres:16-alpine
    container_name: agency-app-postgres
    environment:
      # IMPORTANT: These values must match your DATABASE_URL in .env
      # If you change DATABASE_URL, update these values accordingly
      # DATABASE_URL format: postgresql://USER:PASSWORD@HOST:PORT/DATABASE
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: DSm3bB27AXzlznDA
      POSTGRES_DB: agency-app
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  minio:
    image: minio/minio:latest
    container_name: agency-app-minio
    command: server /data --console-address ":9001"
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - minio_data:/data
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3

volumes:
  postgres_data:
  minio_data:
