packages:
  - apps/*
  - packages/*
  - tooling/*
catalog:
  # Build tools
  eslint: ^9.28.0
  prettier: ^3.5.3
  tailwindcss: 4.1.11
  "@tailwindcss/postcss": 4.1.11
  typescript: ^5.8.3
  
  # Core dependencies
  zod: ^3.25.49
  "@t3-oss/env-nextjs": ^0.13.6
  dotenv-cli: ^8.0.0
  
  # Database
  drizzle-orm: ^0.36.0
  drizzle-zod: ^0.5.1
  postgres: ^3.4.4
  
  # Framework
  hono: ^4.7.11
  
  # Payment & Commerce
  stripe: ^18.3.0
  
  # Data processing
  papaparse: ^5.5.3
  
  # Types
  "@types/node": ^22.15.31
  
  # tRPC & data fetching
  "@tanstack/react-query": ^5.80.7
  "@trpc/client": ^11.4.0
  "@trpc/tanstack-react-query": ^11.4.0
  "@trpc/server": ^11.4.0
  
  # UI libraries
  clsx: ^2.1.1
  class-variance-authority: ^0.7.1
  tailwind-merge: ^3.3.1
  lucide-react: ^0.525.0
  
  # Radix UI
  "@radix-ui/react-avatar": ^1.1.10
  "@radix-ui/react-checkbox": ^1.3.2
  "@radix-ui/react-dialog": ^1.1.14
  "@radix-ui/react-dropdown-menu": ^2.1.15
  "@radix-ui/react-label": ^2.1.7
  "@radix-ui/react-select": ^2.2.5
  "@radix-ui/react-separator": ^1.1.7
  "@radix-ui/react-slot": ^1.2.3
  "@radix-ui/react-switch": ^1.2.5
  "@radix-ui/react-tabs": ^1.1.12
  "@radix-ui/react-toast": ^1.2.4
  
  # Auth
  better-auth: ^1.3.7
  
catalogs:
  react19:
    react: 19.0.0
    react-dom: 19.0.0
    "@types/react": ^19.1.6
    "@types/react-dom": ^19.1.5
onlyBuiltDependencies:
  - esbuild